### ISSUE TITLE
你这个更新好快 请问你是用机器人每天自动拉取更新吗

### ISSUE THREAD

**Issue by gcphym** [godros/openwrt-app#1]
自己手动拉取的

**Comment by gcphym** [comment]
请问我拉取 ``` svn co https://github.com/godros/openwrt-luciapps/branches/luci19/smartdns``` 提示 ```svn: E235000: In file '/build/subversion-Lv3Qkk/subversion-1.9.7/subversion/libsvn_wc/wc_db.c' line 1651: assertion failed (SVN_IS_VALID_REVNUM(changed_rev))
Aborted (core dumped)``` 怎么办

**Comment by godros** [comment]
svn export --force https://github.com/godros/openwrt-app/branches/luci19/luci-app-godproxy package/diy/luci-app-godproxy

这样的例子。
